# Uncomment the next line to define a global platform for your project
platform :ios, ‘7.0’

target 'DL_student' do
# Comment the next line if you're not using Swift and don't want to use dynamic #frameworks
# use_frameworks!

# Pods for DL_student
pod 'SDWebImage', '~>3.8'
pod 'AFNetworking', '~> 3.1.0’

end